### ISSUE TITLE
Simulink models with model references break the adapter

### ISSUE THREAD

**Issue by andresbh** [ld4mbse/oslc-adapter-simulink#2]
I tested the adapter with a model with an embedded referenced model. Both models were in the directory but did not appear in the OSLC. also none of the other sample models appeared listed. After removing the model with the model reference the OSLC links appeared again.

**Comment by axelreichwein** [comment]
In what Simulink version are the models that you are trying to use? Which file ending do they have?

**Comment by andresbh** [comment]
Just saw that is one of the newer MATLAB versions and not in your supported list, namely 2016a. This is probably the issue.
